version: "3"
services:
  nginx.docker:
    container_name: "php_nginx"
    image: php_nginx
    user: root
    working_dir: /app/
    volumes:
      - ./:/app/
    expose:
      - 3000
      - 81
    ports:
      - 3000:3000
      - 81:81
    command: "/./app/docker/nginx/start.sh"
