version: "3"
services:
  nginx.docker:
    container_name: "php_nginx"
    image: php_nginx
    user: root
    working_dir: /app/
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
      - 80:80
      - 9003:9003
    command: "/./app/docker/nginx/start.sh"
